<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.0" language="fr_FR" sourcelanguage="">
<context>
    <name>@default</name>
    <message>
        <location filename="ufwi_rpcd/core/base_service.py" line="114"/>
        <source>callService(cookie, component, service, *args) requires at least 3 parameters</source>
        <translation>callService(cookie, component, service, *args) nécessite au moins 3 arguments</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/core.py" line="383"/>
        <source>No component registered with this name (%s)</source>
        <translation>Aucun composant n&apos;est inscrit sous ce nom (%s)</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/session.py" line="338"/>
        <source>Invalid login or password</source>
        <translation>Identifiant de connexion ou mot de passe incorrect</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/auth/auth_ldap.py" line="53"/>
        <source>Missing parameters to build LDAP object: %s</source>
        <translation>Paramètres absents pour construire l&apos;objet LDAP: %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/auth/auth_file.py" line="42"/>
        <source>%s key is missing in configuration</source>
        <translation>La clé %s est absente de la configuration</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/base.py" line="414"/>
        <source>Unable to connect to &quot;%s&quot;: %s</source>
        <translation type="unfinished">Connexion à «%s» impossible: %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/session.py" line="371"/>
        <source>Invalid session cookie %s: expired session (timeout=%s)</source>
        <translation>Cookie de session %s incorrect: session expirée (délai d&apos;expiration=%s)</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/base.py" line="247"/>
        <source>XML-RPC error on calling %s: %s</source>
        <translation type="unfinished">Erreur XML-RPC lors de l&apos;appel de %s: %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/lock.py" line="350"/>
        <source>Invalid lock key: %s</source>
        <translation>Clé de verrou incorrecte: %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/acl_sqlite.py" line="63"/>
        <source>Version of database (%s) is not supported (required: %s)</source>
        <translation>La version de la base de données (%s) n&apos;est pas supportée (version requise: %s)</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/session.py" line="264"/>
        <source>Invalid client name: need a string with length in 3..20</source>
        <translation>Nom de client incorrect: la longueur de la chaîne doit être en 3..20</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/session.py" line="267"/>
        <source>Invalid protocol version: need a string with length in 3..10</source>
        <translation>Version de protocole incorrecte: la longueur de la chaîne doit être en 3..10</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/session.py" line="272"/>
        <source>Invalid protocol version: %s</source>
        <translation>Version de protocole incorrecte: %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/session.py" line="391"/>
        <source>Unable to generate a session cookie!</source>
        <translation>Impossible de générer un cookie de session!</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/auth/auth_ldap.py" line="44"/>
        <source>LDAP support isn&apos;t activated</source>
        <translation>Le support LDAP n&apos;est pas activé</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/auth/simple_auth.py" line="67"/>
        <source>%s is not a valid type</source>
        <translation>%s n&apos;est pas un type correct</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/auth/auth_radius.py" line="54"/>
        <source>Missing parameters to build Radius object: %s</source>
        <translation>Paramètres manquants pour construire un objet Radius: %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/base.py" line="179"/>
        <source>Unable to connect to %s: %s (error #%s)</source>
        <translation type="unfinished">Connexion à %s impossible: %s (erreur #%s)</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/base.py" line="291"/>
        <source>Error #%s</source>
        <translation type="unfinished">Erreur #%s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/base.py" line="411"/>
        <source>XML-RPC error on getting server version: %s</source>
        <translation type="unfinished">Erreur XML-RPC lors de l&apos;obtention de la version du serveur: %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/auth/simple_auth.py" line="121"/>
        <source>password cannot be empty</source>
        <translation>Le mot de passe ne peut pas être vide</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/session.py" line="278"/>
        <source>Only a user can create a session!</source>
        <translation>Seul un utilisateur peut créer une session!</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/acl_sqlite.py" line="50"/>
        <source>ACL database file (%s) does not exist!</source>
        <translation>Le fichier de base de données de règles (%s) n&apos;existe pas!</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/context.py" line="135"/>
        <source>Context: broken reference to the session! (session killed?)</source>
        <translation>Contexte: référence à la session cassée! (Session supprimée ?)</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/core.py" line="420"/>
        <source>You are not allowed to access the %s component</source>
        <translation>Vous n&apos;avez pas le droit d&apos;accéder au composant %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/core.py" line="471"/>
        <source>You are not allowed to access the %s service</source>
        <translation>Vous n&apos;avez pas le droit d&apos;accéder au service %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/lock.py" line="294"/>
        <source>The &quot;%s&quot; lock is not available</source>
        <translation>Le verrou «%s» n&apos;est pas disponible</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/lock.py" line="312"/>
        <source>You already own the &quot;%s&quot; lock</source>
        <translation>Vous possédez déjà le verrou «%s»</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/lock.py" line="315"/>
        <source>The &quot;%s&quot; lock is already owned by %s</source>
        <translation>Le verrou «%s» appartient déjà à %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/lock.py" line="322"/>
        <source>The &quot;%s&quot; lock is already owned by the %s component</source>
        <translation>Le verrou «%s» appartient déjà au composant %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/lock.py" line="362"/>
        <source>The &quot;%s&quot; lock is not acquired!</source>
        <translation>Le verrou «%s» n&apos;est pas attribué!</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/lock.py" line="369"/>
        <source>The &quot;%s&quot; lock, owned by %s, can not be released!</source>
        <translation>Le verrou «%s», qui appartient à %s, ne peut pas être libéré!</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/lock.py" line="374"/>
        <source>The &quot;%s&quot; lock, owned by the %s component, can not be released!</source>
        <translation>Le verrou «%s», qui appartient au composant %s, ne peut pas être libéré!</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/session.py" line="281"/>
        <source>You already own a session!</source>
        <translation>Vous possédez déjà une session!</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/streaming.py" line="48"/>
        <source>Stream period (%s) is shorter than 1 second</source>
        <translation>La période de flux (%s) est inférieure à 1 seconde</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/base.py" line="176"/>
        <source>Connection refused to %s!
Is the NuCentral server running and listening on port %s?</source>
        <translation type="unfinished">Connexion à %s refusée! Est-ce que le serveur NuCentral fonctionne et écoute sur le port %s ?</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/base.py" line="209"/>
        <source>User session has terminated. Please restart the application to create a new session.</source>
        <translation type="unfinished">La session utilisateur est terminée. Veuillez redémarrer l&apos;application pour créer une nouvelle session.</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/base.py" line="331"/>
        <source>The server version (%s) is different from the client version (%s)!</source>
        <translation type="unfinished">La version du serveur (%s) est différente de la version du client (%s)!</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/acl_sqlite.py" line="58"/>
        <source>Unable to open the ACL database (%s): %s</source>
        <translation>Impossible d&apos;ouvrir la base de données de règles (%s): %s
</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/base.py" line="225"/>
        <source>call() requires at least 2 arguments (component, service)</source>
        <translation type="unfinished">call() nécessite au moins 2 arguments (composant, service)</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/ssl_config.py" line="39"/>
        <source>Please specify a private key.</source>
        <translation>Veuillez indiquer une clé privée</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/ssl_config.py" line="41"/>
        <source>Please specify a certificate.</source>
        <translation>Veuillez indiquer un certificat</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/core.py" line="432"/>
        <source>The %s component has no %s() service</source>
        <translation>Le composant %s n&apos;a pas de service %s()</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/context.py" line="111"/>
        <source>A context requires a user or component session</source>
        <translation>Un contexte nécessite une session utilisateur ou composant</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/streaming.py" line="232"/>
        <source>Only authenticated users can use the %s service</source>
        <translation>Seuls les utilisateurs authentifiés peuvent utiliser le service %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/lock.py" line="422"/>
        <source>You need a session to call the %s service</source>
        <translation>Une session est nécessaire pour appeler le service %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/core_component.py" line="194"/>
        <source>SSL is disabled</source>
        <translation>Le SSL est désactivé</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/session.py" line="380"/>
        <source>The %s user can not use the  %s session: the source address is different.</source>
        <translation>L&apos;utilisateur %s ne peut pas utiliser la session %s: l&apos;adresse source est différente</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/__init__.py" line="35"/>
        <source>EdenWall</source>
        <translation>EdenWall</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/__init__.py" line="39"/>
        <source>NuFirewall</source>
        <translation>NuFirewall</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/base.py" line="406"/>
        <source>The connection was rejected during the SSL handshake, check your SSL configuration.</source>
        <translation type="unfinished">La connexion a été rejetée pendant le handshake SSL; veuillez vérifier votre configuration SSL.</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/__init__.py" line="36"/>
        <source>Edenwall Administration Suite</source>
        <translation>Edenwall Administration Suite</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/__init__.py" line="37"/>
        <source>EAS</source>
        <translation>EAS</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/__init__.py" line="40"/>
        <source>NuFirewall Administration Suite</source>
        <translation>NuFirewall Administration Suite</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/client/__init__.py" line="41"/>
        <source>NuFW-AS</source>
        <translation>NuFW-AS</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/auth/auth.py" line="33"/>
        <source>%s is not a valid group name.</source>
        <translation>%s n&apos;est pas un nom de groupe correct</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/auth/simple_auth.py" line="54"/>
        <source>%s is not a valid user name.</source>
        <translation>%s n&apos;est pas un nom d&apos;utilisateur correct</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/auth/simple_auth.py" line="37"/>
        <source>The password you entered is not valid.</source>
        <translation>Le mot de passe que vous avez indiqué est incorrect</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="129"/>
        <source>Yes</source>
        <translation>Oui</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="131"/>
        <source>No</source>
        <translation>Non</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="154"/>
        <source>%s h</source>
        <translation>%s h</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="156"/>
        <source>%s min</source>
        <translation>%s min</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="164"/>
        <source>%s sec</source>
        <translation>%s sec</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="167"/>
        <source>%.1f sec</source>
        <translation>%.1f sec</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="170"/>
        <source>%s ms</source>
        <translation>%s ms</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="182"/>
        <source>Today</source>
        <translation>Aujourd&apos;hui</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="184"/>
        <source>Yesterday</source>
        <translation>Hier</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="186"/>
        <source>Tomorrow</source>
        <translation>Demain</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="193"/>
        <source>%(date)s at %(time)s</source>
        <translation>%(date)s à %(time)s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/radius_client.py" line="204"/>
        <source>This parameter cannot be empty: &apos;user&apos;.</source>
        <translation>Ce champ ne peut pas être vide: «utilisateur»</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/radius_client.py" line="206"/>
        <source>This parameter cannot be empty: &apos;password&apos;.</source>
        <translation>Ce champ ne peut pas être vide: «mot de passe»</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/radius_client.py" line="208"/>
        <source>This parameter cannot be empty: &apos;shared secret&apos;.</source>
        <translation>Ce champ ne peut pas être vide: «secret partagé»</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/radius_client.py" line="210"/>
        <source>This parameter should be an integer: &apos;nas port&apos;</source>
        <translation>Ce champ doit être un nombre entier: «port nas»</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="69"/>
        <source>OK</source>
        <translation>OK</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="70"/>
        <source>unable to get issuer certificate</source>
        <translation>impossible d&apos;obtenir le certificat de l&apos;émetteur</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="71"/>
        <source>unable to get certificate CRL</source>
        <translation>impossible d&apos;obtenir la CRL du certificat</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="72"/>
        <source>unable to decrypt certificate signature</source>
        <translation>impossible de déchiffrer la signature du certificat</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="73"/>
        <source>unable to decrypt CRL signature</source>
        <translation>impossible de déchiffrer la signature de la CRL</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="74"/>
        <source>unable to decode issuer public key</source>
        <translation>impossible de décoder la clé publique de l&apos;émetteur</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="75"/>
        <source>certificate signature failure</source>
        <translation>échec de signature du certificat</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="76"/>
        <source>CRL signature failure</source>
        <translation>échec de signature de la CRL</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="77"/>
        <source>certificate is not yet valid</source>
        <translation>le certificat n&apos;est pas encore valide</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="78"/>
        <source>CRL is not yet valid</source>
        <translation>la CRL n&apos;est pas encore valide</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="79"/>
        <source>certificate has expired</source>
        <translation>le certificat a expiré</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="80"/>
        <source>CRL has expired</source>
        <translation>la CRL a expiré</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="81"/>
        <source>format error in certificate notBefore field</source>
        <translation>erreur de format dans le champ notBefore du certificat</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="82"/>
        <source>format error in certificate notAfter field</source>
        <translation>erreur de format dans le champ notAfter du certificat</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="83"/>
        <source>format error in CRL lastUpdate field</source>
        <translation>erreur de format dans le champ lastUpdate de la CRL</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="84"/>
        <source>format error in CRL nextUpdate field</source>
        <translation>erreur de format dans le champ nextUpdate de la CRL</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="85"/>
        <source>out of memory</source>
        <translation>mémoire saturée</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="86"/>
        <source>self signed certificate</source>
        <translation>certificat autosigné</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="87"/>
        <source>self signed certificate in certificate chain</source>
        <translation>certificat autosigné dans la chaîne de certificats</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="88"/>
        <source>unable to get local issuer certificate</source>
        <translation>impossible d&apos;obtenir le certificat de l&apos;émetteur local</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="89"/>
        <source>unable to verify the first certificate</source>
        <translation>impossible de vérifier le premier certificat</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="90"/>
        <source>certificate chain too long</source>
        <translation>chaîne de certificats trop longue</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="91"/>
        <source>certificate revoked</source>
        <translation>certificat révoqué</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="92"/>
        <source>invalid CA certificate</source>
        <translation>certificat d&apos;AC incorrect</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="93"/>
        <source>invalid non-CA certificate (has CA markings)</source>
        <translation>certificat non-AC incorrect (contient des marqueurs d&apos;AC)</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="94"/>
        <source>path length constraint exceeded</source>
        <translation>chemin trop long</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="95"/>
        <source>proxy path length constraint exceeded</source>
        <translation>chemin de proxy trop long</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="96"/>
        <source>proxy certificates not allowed, please set the appropriate flag</source>
        <translation>certificats de proxy non autorisés; veuillez indiquer le marqueur approprié</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="97"/>
        <source>unsupported certificate purpose</source>
        <translation>objet de certificat non supporté</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="98"/>
        <source>certificate not trusted</source>
        <translation>certificat suspect</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="99"/>
        <source>certificate rejected</source>
        <translation>certificat rejeté</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="100"/>
        <source>application verification failure</source>
        <translation>échec de vérification de l&apos;application </translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="101"/>
        <source>subject issuer mismatch</source>
        <translation>non-correspondance de l&apos;émetteur du sujet</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="102"/>
        <source>authority and subject key identifier mismatch</source>
        <translation>non-correspondance de l&apos;identificateur de clé du sujet et de l&apos;autorité</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="103"/>
        <source>authority and issuer serial number mismatch</source>
        <translation>non-correspondance du numéro de série de l&apos;émetteur et de l&apos;autorité</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="104"/>
        <source>key usage does not include certificate signing</source>
        <translation>l&apos;utilisation de la clé ne couvre pas la signature de certificats</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="105"/>
        <source>unable to get CRL issuer certificate</source>
        <translation>impossible d&apos;obtenir le certificat de l&apos;émetteur de la CRL</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="106"/>
        <source>unhandled critical extension</source>
        <translation>extension critique non gérée</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="107"/>
        <source>key usage does not include CRL signing</source>
        <translation>l&apos;utilisation de la clé ne couvre pas la signature de CRL</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="108"/>
        <source>key usage does not include digital signature</source>
        <translation>l&apos;utilisation de la clé ne couvre pas la signature numérique</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="109"/>
        <source>unhandled critical CRL extension</source>
        <translation>extension de CRL critique non gérée</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="110"/>
        <source>invalid or inconsistent certificate extension</source>
        <translation>extension de certificat incorrecte ou incohérente</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="111"/>
        <source>invalid or inconsistent certificate policy extension</source>
        <translation>extension de politique de certificat incorrecte ou incohérente</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="112"/>
        <source>no explicit policy</source>
        <translation>pas de politique explicite</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="113"/>
        <source>RFC 3779 resource not subset of parent&apos;s resources</source>
        <translation>La ressource RFC 3779 n&apos;est pas un sous-ensemble des ressources parentes</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/ssl_errors.py" line="117"/>
        <source>Unknown SSL error code: %i</source>
        <translation>Code d&apos;erreur SSL inconnu: %i</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/module_loader.py" line="55"/>
        <source>Unable to read &apos;[modules]&apos; section in the configuration</source>
        <translation>Impossible de lire la section «[modules]» dans la configuration</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/session.py" line="437"/>
        <source>You are not allowed to kill other users&apos; sessions</source>
        <translation>Vous n&apos;êtes pas autorisé à fermer les sessions des autres utilisateurs</translation>
    </message>
    <message numerus="yes">
        <location filename="ufwi_rpcd/common/human.py" line="149"/>
        <source>%s day(s)</source>
        <translation>
            <numerusform>%s jour(s)</numerusform>
            <numerusform></numerusform>
        </translation>
    </message>
    <message numerus="yes">
        <location filename="ufwi_rpcd/common/human.py" line="189"/>
        <source>%s day(s) ago</source>
        <translation>
            <numerusform>Il y a %s jour(s)</numerusform>
            <numerusform></numerusform>
        </translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="75"/>
        <source>No certificate set</source>
        <translation>Pas de certificat défini</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="75"/>
        <source>No certificate has been set yet</source>
        <translation>Aucun certificat n&apos;a encore été défini</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="76"/>
        <source>No key set</source>
        <translation>Aucune clé définie</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="77"/>
        <source>No CA is set</source>
        <translation>Aucune AC n&apos;a encore été définie</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="77"/>
        <source>No certificate authority has been set yet</source>
        <translation>Aucune autorité de certification n&apos;a encore été définie</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="78"/>
        <source>No CRL set</source>
        <translation>Aucune CRL définie</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="78"/>
        <source>No certificate revocation list has been set yet</source>
        <translation>Aucune liste de révocation n&apos;a encore été définie</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="88"/>
        <source>Invalid certificate</source>
        <translation>Certificat incorrect</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="99"/>
        <source>Invalid key</source>
        <translation>Clé incorrecte</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="109"/>
        <source>Invalid CA</source>
        <translation>AC incorrecte</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="116"/>
        <source>CRL set</source>
        <translation>CRL définie</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="119"/>
        <source>Invalid CRL</source>
        <translation>CRL incorrecte</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/use_cert_component.py" line="154"/>
        <source>No CRL has previously been uploaded. CRL check cannot be enabled.</source>
        <translation>Aucune CRL n&apos;a été déposée. Impossible d&apos;activer la vérification de la CRL</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/variables_store.py" line="85"/>
        <source>No such key: %s</source>
        <translation>La clé %s est introuvable</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/variables_store.py" line="95"/>
        <source>Cannot set a list as a value</source>
        <translation>Impossible d&apos;utiliser une liste comme valeur</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/variables_store.py" line="225"/>
        <source>Unable to write into %s XML file: %s</source>
        <translation>Impossible d&apos;écrire dans le fichier XML %s: %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/variables_store.py" line="273"/>
        <source>Unable to open %s XML file: %s!</source>
        <translation>Impossible d&apos;ouvrir le fichier XML %s: %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/variables_store.py" line="288"/>
        <source>XML root is not %s</source>
        <translation>La racine XML n&apos;est pas %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/variables_store.py" line="295"/>
        <source>VariablesStore version expected: %s, got %s</source>
        <translation>Version VariablesStore attendue: %s; version obtenue: %s</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/variables_store.py" line="349"/>
        <source>Path too long, can not recurse past tree leafs (values)</source>
        <translation>Chemin trop long, impossible d&apos;aller plus loin que les feuilles (valeurs) d&apos;un arbre</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/versionning.py" line="115"/>
        <source>Commit message cannot be empty.</source>
        <translation>Le message de commit ne peut pas être vide</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/backend/variables_store.py" line="298"/>
        <source>VariablesStore version not found (expected version=&quot;%s&quot;)</source>
        <translation>Version VariablesStore introuvable (version attendue: «%s»</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="214"/>
        <source>KB</source>
        <translation>Ko</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="214"/>
        <source>MB</source>
        <translation>Mo</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="214"/>
        <source>GB</source>
        <translation>Go</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/common/human.py" line="214"/>
        <source>TB</source>
        <translation>To</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/streaming.py" line="202"/>
        <source>You are not allowed to delete this streaming</source>
        <translation>Vous n&apos;avez pas le droit de supprimer ce flux</translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/config/manager.py" line="494"/>
        <source>Reloading full configuration</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/config/manager.py" line="534"/>
        <source>No changes saved: there is nothing to apply</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/config/manager.py" line="546"/>
        <source>Can not apply configuration: high availability is enabled and node is not active</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/config/manager.py" line="584"/>
        <source>Unknow High Availability status (%(STATUS)s), node is considered active</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/config/manager.py" line="948"/>
        <source>Putting the saved configuration on hold if any.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/config/manager.py" line="953"/>
        <source>Put the saved configuration on hold</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/config/manager.py" line="973"/>
        <source>There was no saved configuration waiting for application.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/config/manager.py" line="961"/>
        <source>Restoring the saved configuration that was on hold, if any.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="ufwi_rpcd/core/config/manager.py" line="967"/>
        <source>Restored the saved configuration that was on hold.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
